name: release
on:
  push:
    branches:
      - master
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Run install
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Git Identity
        run: |
          git config --global user.name 'pvds'
          git config --global user.email 'pvdsteen@gmail.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run publish
        run: yarn publish-ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
